title: CARVE
description: "Cade Andgreg's RISC-V Emulator"
baseurl: "/CARVE"
url: "https://gcrois.github.io/CARVE/"

permalink: pretty
exclude: ["*.gemspec", "*.gem", "Gemfile", "Gemfile.lock"]

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
